version: "3.8"                                          # 파일 규격 버전
services:                                               # 이 항목 밑에 실행하려는 컨테이너들을 정의
  today-redis:                        # 서비스명
    container_name: today-redis       # 컨테이너 명
    build:
      dockerfile: Dockerfile
      context: ./redis
    image: sh7824/today-redis
    ports:
      - "6379:6379"
  jenkins:
    container_name: jenkins
    build:
      context: jenkins-dockerfile
      dockerfile: Dockerfile
    restart: unless-stopped
    user: root
    ports:
      - 8888:8080
      - 50000:50000
    volumes:
      - /home/ec2-user/jenkins:/var/jenkins_home
      - /home/ec2-user/.ssh:/root/.ssh
  today-database:
    container_name: today-database
    build:
      dockerfile: Dockerfile
      context: ./database
    image: sh7824/today-database
    environment:
      - MARIADB_DATABASE=today
      - MARIADB_ROOT_PASSWORD=${SPRING_DATASOURCE_PASSWORD}
    volumes:
      - ./database/config:/etc/mysql/conf.d
      - ./database/init:/docker-entrypoint-initdb.d
    ports:
      - "3306:3306"
  today-app:
    container_name: today-app
    build: .
    depends_on:
      - today-database
      - today-redis
    image: sh7824/today-app
    environment:
      - SPRING_DATASOURCE_USERNAME=${SPRING_DATASOURCE_USERNAME}
      - SPRING_DATASOURCE_PASSWORD=${SPRING_DATASOURCE_PASSWORD}
      - SPRING_PROFILES_ACTIVE=${SPRING_PROFILES_ACTIVE}
    ports:
      - "80:8080"
    restart: always