version: "3.8"
services:
  today-redis:
    container_name: today-redis
    build:
      dockerfile: Dockerfile
      context: ./redis
    image: sh7824/today-redis
    ports:
      - "6379:6379"
  today-database:
    container_name: today-database
    build:
      dockerfile: Dockerfile
      context: ./database
    image: sh7824/today-database
    environment:
      - MARIADB_DATABASE=today
      - MARIADB_ROOT_PASSWORD=${SPRING_DATASOURCE_PASSWORD}
    volumes:
      - ./database/config:/etc/mysql/conf.d
      - ./database/init:/docker-entrypoint-initdb.d
    ports:
      - "3306:3306"